version: '3'

services:
  django_app:
    build: .
    env_file:
      - .env
    entrypoint: 
      - /app/server-entrypoint.sh
    volumes:
      - static_vol:/app/core/static
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  celery:
    build: .
    command:
      - celery -A djangopoc worker --loglevel=info
    env_file:
      - .env
    entrypoint: 
      - /app/worker-entrypoint.sh
    volumes:
      - static_vol:/app/core/static
    depends_on:
      - django_app
      - redis
  nginx:
    build: ./nginx
    volumes:
      - static_vol:/app/core/static
    ports:
      - "80:80"
    depends_on:
      - django_app

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: pocdb
      POSTGRES_USER: yash      # Change if needed
      POSTGRES_PASSWORD: Yash1234  # Change to a strong password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    expose:
      - 6379
volumes:
  static_vol:
  postgres_data: