# Generated by Django 5.0 on 2024-01-02 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_wallet_farmer_wallet_investor_wallet'),
        ('farmer', '0002_icoentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICOTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('per_entity_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.icoentity')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.investor')),
            ],
            options={
                'verbose_name_plural': 'ICO Transactions',
            },
        ),
    ]
