# Generated by Django 5.0 on 2023-12-28 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_wallet_farmer_wallet_investor_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('Rabi', 'Rabi'), ('Kharif', 'Kharif')], max_length=6)),
                ('year', models.IntegerField()),
                ('crop', models.CharField(max_length=20)),
                ('area_cultivated', models.FloatField()),
                ('revenue', models.FloatField()),
                ('expenses', models.FloatField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farmer')),
            ],
        ),
    ]
