# Generated by Django 5.0 on 2023-12-29 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wallet_farmer_wallet_investor_wallet'),
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICOEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isVerified', models.BooleanField(default=False)),
                ('crop', models.CharField(max_length=20)),
                ('land_area', models.FloatField()),
                ('capital', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('sold_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closes_on', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farmer')),
            ],
        ),
    ]
