# Generated by Django 5.0 on 2024-01-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_icoentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='icoentity',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='icoentity',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
