# Generated by Django 5.0 on 2024-01-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_icoentity_is_rejected_icoentity_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='icoentity',
            name='is_return_provided',
            field=models.BooleanField(default=False),
        ),
    ]
